# 基础配置
spring:
  application:
    name: cms
  profiles:
    active: dev
server:
  port: 8888

--- # 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mxycms
    username: root
    password: root

--- # 中间件
spring:
  data:
    redis:
      url: redis://@127.0.0.1:6379

--- # 安全配置
spring:
  security:
    user:
      name: admin
      password: admin

--- # prod 配置
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      url: redis://@127.0.0.1:6379